In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

C:\Users\ADMIN\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
# Reading the Dataset
dataset=pd.read_csv('Social_Network_Ads.csv')
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset=dataset.astype(int)
dataset

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [4]:
dataset.columns

Index(['User ID', 'Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [5]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']
indep

Age  EstimatedSalary  Gender_Male
0     19            19000            1
1     35            20000            1
2     26            43000            0
3     27            57000            0
4     19            76000            1
..   ...              ...          ...
395   46            41000            0
396   51            23000            1
397   50            20000            0
398   36            33000            1
399   49            36000            0

[400 rows x 3 columns]

In [6]:
dep

0      0
1      0
2      0
3      0
4      0
      ..
395    1
396    1
397    1
398    0
399    1
Name: Purchased, Length: 400, dtype: int32

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)


In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
from sklearn.model_selection import GridSearchCV

param_grid = {'criterion':['gini','entropy'],
              'max_features': ['auto','sqrt','log2'],
              'n_estimators':[10,100]} 


grid = GridSearchCV(RandomForestClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train, y_train) 
 

Fitting 5 folds for each of 12 candidates, totalling 60 fits


C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning: 
20 fits failed out of a total of 60.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
7 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\ADMIN\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\ADMIN\anaconda3\Lib\site-packages\s

GridSearchCV(estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             scoring='f1', verbose=3)

In [14]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
print(re)
grid_predictions = grid.predict(X_test) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)

# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

{'mean_fit_time': array([0.        , 0.        , 0.03436632, 0.3158978 , 0.02811918,
       0.31867323, 0.        , 0.00312452, 0.03436704, 0.32179856,
       0.02811856, 0.28118358]), 'std_fit_time': array([0.        , 0.        , 0.00624886, 0.01535557, 0.00624912,
       0.02338109, 0.        , 0.00624905, 0.00624874, 0.01593097,
       0.00624809, 0.06402704]), 'mean_score_time': array([0.        , 0.        , 0.01249743, 0.03436713, 0.01249633,
       0.02811899, 0.        , 0.        , 0.00624871, 0.01874566,
       0.00937195, 0.0218699 ]), 'std_score_time': array([0.        , 0.        , 0.01168976, 0.01530478, 0.01168826,
       0.01168948, 0.        , 0.        , 0.00765308, 0.00624871,
       0.00765216, 0.00765298]), 'param_criterion': masked_array(data=['gini', 'gini', 'gini', 'gini', 'gini', 'gini',
                   'entropy', 'entropy', 'entropy', 'entropy', 'entropy',
                   'entropy'],
             mask=[False, False, False, False, False, False, False, Fa

In [15]:
print(grid.best_params_)

{'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}


In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time  \
0        0.000000      0.000000         0.000000        0.000000   
1        0.000000      0.000000         0.000000        0.000000   
2        0.034366      0.006249         0.012497        0.011690   
3        0.315898      0.015356         0.034367        0.015305   
4        0.028119      0.006249         0.012496        0.011688   
5        0.318673      0.023381         0.028119        0.011689   
6        0.000000      0.000000         0.000000        0.000000   
7        0.003125      0.006249         0.000000        0.000000   
8        0.034367      0.006249         0.006249        0.007653   
9        0.321799      0.015931         0.018746        0.006249   
10       0.028119      0.006248         0.009372        0.007652   
11       0.281184      0.064027         0.021870        0.007653   

   param_criterion param_max_features param_n_estimators  \
0             gini               auto                 10   
1             gini               auto                100   
2             gini               sqrt                 10   
3             gini               sqrt                100   
4             gini               log2                 10   
5             gini               log2                100   
6          entropy               auto                 10   
7          entropy               auto                100   
8          entropy               sqrt                 10   
9          entropy               sqrt                100   
10         entropy               log2                 10   
11         entropy               log2                100   

                                               params  split0_test_score  \
0   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
1   {'criterion': 'gini', 'max_features': 'auto', ...                NaN   
2   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.800000   
3   {'criterion': 'gini', 'max_features': 'sqrt', ...           0.727273   
4   {'criterion': 'gini', 'max_features': 'log2', ...           0.764706   
5   {'criterion': 'gini', 'max_features': 'log2', ...           0.764706   
6   {'criterion': 'entropy', 'max_features': 'auto...                NaN   
7   {'criterion': 'entropy', 'max_features': 'auto...                NaN   
8   {'criterion': 'entropy', 'max_features': 'sqrt...           0.764706   
9   {'criterion': 'entropy', 'max_features': 'sqrt...           0.800000   
10  {'criterion': 'entropy', 'max_features': 'log2...           0.727273   
11  {'criterion': 'entropy', 'max_features': 'log2...           0.800000   

    split1_test_score  split2_test_score  split3_test_score  \
0                 NaN                NaN                NaN   
1                 NaN                NaN                NaN   
2            0.810811           0.780488           0.842105   
3            0.850000           0.809524           0.900000   
4            0.789474           0.809524           0.810811   
5            0.871795           0.809524           0.900000   
6                 NaN                NaN                NaN   
7                 NaN                NaN                NaN   
8            0.810811           0.780488           0.871795   
9            0.871795           0.809524           0.900000   
10           0.810811           0.731707           0.900000   
11           0.842105           0.809524           0.900000   

    split4_test_score  mean_test_score  std_test_score  rank_test_score  
0                 NaN              NaN             NaN                9  
1                 NaN              NaN             NaN                9  
2            0.918919         0.830465        0.048522                5  
3            0.923077         0.841975        0.069597                4  
4            0.888889         0.812681        0.041620                7  
5            0.947368         0.858679        0.064796                3  
6          

In [18]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)


The f1_macro value for best parameter {'criterion': 'entropy', 'max_features': 'sqrt', 'n_estimators': 100}: 0.9256751954513147


In [19]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [ 4 45]]


In [20]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.95      0.93      0.94        85
           1       0.88      0.92      0.90        49

    accuracy                           0.93       134
   macro avg       0.92      0.92      0.92       134
weighted avg       0.93      0.93      0.93       134



In [21]:
table_pr=pd.DataFrame()

In [22]:
print(X_test)

[[-0.76605872  0.52531653  1.00754728]
 [ 0.02298918 -0.57354963 -0.99250926]
 [-0.27290378  0.16892751  1.00754728]
 [-0.76605872  0.28772385 -0.99250926]
 [-0.27290378 -0.57354963 -0.99250926]
 [-1.06195168 -1.4645222   1.00754728]
 [-0.66742773 -1.61301763 -0.99250926]
 [-0.1742728   2.21816441  1.00754728]
 [-1.94963056 -0.03896609 -0.99250926]
 [ 0.91066806 -0.78144323  1.00754728]
 [-0.76605872 -0.60324872  1.00754728]
 [-0.96332069 -0.42505421 -0.99250926]
 [-0.07564181 -0.42505421  1.00754728]
 [ 0.12162016  0.22832568  1.00754728]
 [-1.75236858  0.49561745  1.00754728]
 [-0.56879674  1.4162891  -0.99250926]
 [-0.07564181  0.22832568  1.00754728]
 [-1.85099957  0.46591836  1.00754728]
 [ 1.69971595  1.80237721 -0.99250926]
 [-0.27290378 -1.40512403  1.00754728]
 [-0.27290378 -0.66264689 -0.99250926]
 [ 0.91066806  2.21816441 -0.99250926]
 [ 0.31888214 -0.54385055 -0.99250926]
 [ 0.91066806  1.05990007  1.00754728]
 [-1.45647562 -1.22692951 -0.99250926]
 [ 1.10793003  2.12906715

In [23]:
table_pr['Age']=X_test["Age"]
table_pr['Gender_male']=X_test["Gender_Male"]
table_pr['Estimated_Salary']=X_test["EstimatedSalary"]
table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [24]:
table_pr.head(134)

Empty DataFrame
Columns: []
Index: []

In [25]:
table_pr.to_csv("cm.csv",index=False)

In [26]:
dataset['']
dataset['Predicted']=grid_predictions

KeyError: ''

In [ ]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

In [ ]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))